/**
 * @license React
 * react-server-dom-webpack-writer.browser.production.min.server.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
(function(){'use strict';(function(w,x){"object"===typeof exports&&"undefined"!==typeof module?x(exports,require("react")):"function"===typeof define&&define.amd?define(["exports","react"],x):(w=w||self,x(w.ReactServerDOMWriter={},w.React))})(this,function(w,x){function G(a,b){if(0!==b.length)if(512<b.length)0<h&&(a.enqueue(new Uint8Array(k.buffer,0,h)),k=new Uint8Array(512),h=0),a.enqueue(b);else{var e=k.length-h;e<b.length&&(0===e?a.enqueue(k):(k.set(b.subarray(0,e),h),a.enqueue(k),b=b.subarray(e)),k=new Uint8Array(512),
h=0);k.set(b,h);h+=b.length}return!0}function d(a){return y.encode(a)}function Q(a,b){"function"===typeof a.error?a.error(b):a.close()}function f(a,b,e,c,d,g,l){this.acceptsBooleans=2===b||3===b||4===b;this.attributeName=c;this.attributeNamespace=d;this.mustUseProperty=e;this.propertyName=a;this.type=b;this.sanitizeURL=g;this.removeEmptyString=l}function C(a,b){if(a!==b){a.context._currentValue=a.parentValue;a=a.parent;var e=b.parent;if(null===a){if(null!==e)throw Error("The stacks must reach the root at the same time. This is a bug in React.");
}else{if(null===e)throw Error("The stacks must reach the root at the same time. This is a bug in React.");C(a,e);b.context._currentValue=b.value}}}function S(a){a.context._currentValue=a.parentValue;a=a.parent;null!==a&&S(a)}function T(a){var b=a.parent;null!==b&&T(b);a.context._currentValue=a.value}function U(a,b){a.context._currentValue=a.parentValue;a=a.parent;if(null===a)throw Error("The depth must equal at least at zero before reaching the root. This is a bug in React.");a.depth===b.depth?C(a,
b):U(a,b)}function V(a,b){var e=b.parent;if(null===e)throw Error("The depth must equal at least at zero before reaching the root. This is a bug in React.");a.depth===e.depth?C(a,e):V(a,e);b.context._currentValue=b.value}function H(a){var b=p;b!==a&&(null===b?T(a):null===a?S(b):b.depth===a.depth?C(b,a):b.depth>a.depth?U(b,a):V(b,a),p=a)}function W(a,b){var e=a._currentValue;a._currentValue=b;var c=p;return p=a={parent:c,depth:null===c?0:c.depth+1,context:a,parentValue:e,value:b}}function X(a){return a._currentValue}
function m(){throw Error("This Hook is not supported in Server Components.");}function ia(){if(!v)throw Error("Refreshing the cache is not supported in Server Components.");}function ja(a){console.error(a)}function ka(a,b,e,c,d){var R=[],l={status:0,fatalError:null,destination:null,bundlerConfig:b,cache:new Map,nextChunkId:0,pendingChunks:0,pingedSegments:R,completedModuleChunks:[],completedJSONChunks:[],completedErrorChunks:[],writtenSymbols:new Map,writtenModules:new Map,writtenProviders:new Map,
identifierPrefix:d||"",identifierCount:1,onError:void 0===e?ja:e,toJSON:function(a,b){return la(l,this,a,b)}};l.pendingChunks++;b=ma(c);a=Y(l,a,b);R.push(a);return l}function D(a,b,e,c){if(null!==e&&void 0!==e)throw Error("Refs cannot be used in server components, nor passed to client components.");if("function"===typeof a)return a(c);if("string"===typeof a)return[q,a,b,c];if("symbol"===typeof a)return a===na?c.children:[q,a,b,c];if(null!=a&&"object"===typeof a){if(a.$$typeof===Z)return[q,a,b,c];
switch(a.$$typeof){case I:var d=a._init;a=d(a._payload);return D(a,b,e,c);case oa:return b=a.render,b(c,void 0);case pa:return D(a.type,b,e,c);case aa:return W(a._context,c.value),[q,a,b,{value:c.value,children:c.children,__pop:ba}]}}throw Error("Unsupported server component type: "+J(a));}function Y(a,b,e){var c={id:a.nextChunkId++,model:b,context:e,ping:function(){var b=a.pingedSegments;b.push(c);1===b.length&&ca(a)}};return c}function qa(a){return Object.prototype.toString.call(a).replace(/^\[object (.*)\]$/,
function(a,e){return e})}function z(a){var b=JSON.stringify(a);return'"'+a+'"'===b?a:b}function J(a){switch(typeof a){case "string":return JSON.stringify(10>=a.length?a:a.substr(0,10)+"...");case "object":if(da(a))return"[...]";a=qa(a);return"Object"===a?"{...}":a;case "function":return"function";default:return String(a)}}function r(a,b){if(da(a)){for(var e="[",c=0;c<a.length;c++){0<c&&(e+=", ");if(6<c){e+="...";break}var d=a[c];e=""+c===b&&"object"===typeof d&&null!==d?e+r(d):e+J(d)}return e+"]"}e=
"{";c=Object.keys(a);for(d=0;d<c.length;d++){0<d&&(e+=", ");if(6<d){e+="...";break}var g=c[d];e+=z(g)+": ";var l=a[g];e=g===b&&"object"===typeof l&&null!==l?e+r(l):e+J(l)}return e+"}"}function la(a,b,e,c){switch(c){case q:return"$"}for(;"object"===typeof c&&null!==c&&(c.$$typeof===q||c.$$typeof===I);)try{switch(c.$$typeof){case q:var d=c;c=D(d.type,d.key,d.ref,d.props);break;case I:var g=c._init;c=g(c._payload)}}catch(t){if("object"===typeof t&&null!==t&&"function"===typeof t.then)return a.pendingChunks++,
a=Y(a,c,p),e=a.ping,t.then(e,e),"@"+a.id.toString(16);E(a,t);a.pendingChunks++;e=a.nextChunkId++;K(a,e,t);return"@"+e.toString(16)}if(null===c)return null;if("object"===typeof c){if(c.$$typeof===Z){d=c.filepath+"#"+c.name;g=a.writtenModules;var l=g.get(d);if(void 0!==l)return b[0]===q&&"1"===e?"@"+l.toString(16):"$"+l.toString(16);try{var f=a.bundlerConfig[c.filepath][c.name];a.pendingChunks++;var n=a.nextChunkId++,h=F(f),k="M"+n.toString(16)+":"+h+"\n";var m=y.encode(k);a.completedModuleChunks.push(m);
g.set(d,n);return b[0]===q&&"1"===e?"@"+n.toString(16):"$"+n.toString(16)}catch(t){return a.pendingChunks++,e=a.nextChunkId++,K(a,e,t),"$"+e.toString(16)}}else{if(c.$$typeof===aa)return b=c._context._globalName,c=a.writtenProviders,e=c.get(e),void 0===e&&(a.pendingChunks++,e=a.nextChunkId++,c.set(b,e),b="P"+e.toString(16)+":"+b+"\n",b=y.encode(b),a.completedJSONChunks.push(b)),"$"+e.toString(16);if(c===ba){a=p;if(null===a)throw Error("Tried to pop a Context at the root of the app. This is a bug in React.");
e=a.parentValue;a.context._currentValue=e===ea?a.context._defaultValue:e;p=a.parent;return}}return c}if("string"===typeof c)return a="$"===c[0]||"@"===c[0]?"$"+c:c,a;if("boolean"===typeof c||"number"===typeof c||"undefined"===typeof c)return c;if("function"===typeof c){if(/^on[A-Z]/.test(e))throw Error("Event handlers cannot be passed to client component props. Remove "+(z(e)+" from these props if possible: "+r(b)+"\nIf you need interactivity, consider converting part of this to a client component."));
throw Error("Functions cannot be passed directly to client components because they're not serializable. Remove "+(z(e)+" ("+(c.displayName||c.name||"function")+") from this object, or avoid the entire object: "+r(b)));}if("symbol"===typeof c){f=a.writtenSymbols;n=f.get(c);if(void 0!==n)return"$"+n.toString(16);n=c.description;if(Symbol.for(n)!==c)throw Error("Only global symbols received from Symbol.for(...) can be passed to client components. The symbol Symbol.for("+(c.description+") cannot be found among global symbols. Remove ")+
(z(e)+" from this object, or avoid the entire object: "+r(b)));a.pendingChunks++;e=a.nextChunkId++;b=F(n);b="S"+e.toString(16)+":"+b+"\n";b=y.encode(b);a.completedModuleChunks.push(b);f.set(c,e);return"$"+e.toString(16)}if("bigint"===typeof c)throw Error("BigInt ("+c+") is not yet supported in client component props. Remove "+(z(e)+" from this object or use a plain number instead: "+r(b)));throw Error("Type "+typeof c+" is not supported in client component props. Remove "+(z(e)+" from this object, or avoid the entire object: "+
r(b)));}function E(a,b){a=a.onError;a(b)}function fa(a,b){null!==a.destination?(a.status=2,Q(a.destination,b)):(a.status=1,a.fatalError=b)}function K(a,b,e){var c="";try{if(e instanceof Error){var d=String(e.message);c=String(e.stack)}else d="Error: "+e}catch(g){d="An error occurred but serializing the error message failed."}e={message:d,stack:c};b="E"+b.toString(16)+":"+F(e)+"\n";b=y.encode(b);a.completedErrorChunks.push(b)}function ca(a){var b=L.current,e=v;L.current=ra;v=a.cache;A=a;try{var c=
a.pingedSegments;a.pingedSegments=[];for(var d=0;d<c.length;d++){var g=c[d];var f=a;H(g.context);try{for(var h=g.model;"object"===typeof h&&null!==h&&h.$$typeof===q;){var n=h;g.model=h;h=D(n.type,n.key,n.ref,n.props)}var k=g.id,m=F(h,f.toJSON),p="J"+k.toString(16)+":"+m+"\n";var t=y.encode(p);f.completedJSONChunks.push(t)}catch(u){if("object"===typeof u&&null!==u&&"function"===typeof u.then){var r=g.ping;u.then(r,r)}else E(f,u),K(f,g.id,u)}}null!==a.destination&&ha(a,a.destination)}catch(u){E(a,u),
fa(a,u)}finally{L.current=b,v=e,A=null}}function ha(a,b){k=new Uint8Array(512);h=0;try{for(var d=a.completedModuleChunks,c=0;c<d.length;c++)if(a.pendingChunks--,!G(b,d[c])){a.destination=null;c++;break}d.splice(0,c);var f=a.completedJSONChunks;for(c=0;c<f.length;c++)if(a.pendingChunks--,!G(b,f[c])){a.destination=null;c++;break}f.splice(0,c);var g=a.completedErrorChunks;for(c=0;c<g.length;c++)if(a.pendingChunks--,!G(b,g[c])){a.destination=null;c++;break}g.splice(0,c)}finally{k&&0<h&&(b.enqueue(new Uint8Array(k.buffer,
0,h)),k=null,h=0)}0===a.pendingChunks&&b.close()}function ma(a){if(a){var b=p;H(null);for(var d=0;d<a.length;d++){var c=a[d],f=c[0];c=c[1];M[f]||(M[f]=x.createServerContext(f,ea));W(M[f],c)}a=p;H(b);return a}return null}var k=null,h=0,y=new TextEncoder,F=JSON.stringify,Z=Symbol.for("react.module.reference"),q=Symbol.for("react.element"),na=Symbol.for("react.fragment"),aa=Symbol.for("react.provider"),oa=Symbol.for("react.forward_ref"),pa=Symbol.for("react.memo"),I=Symbol.for("react.lazy"),ea=Symbol.for("react.default_value"),
B="children dangerouslySetInnerHTML defaultValue defaultChecked innerHTML suppressContentEditableWarning suppressHydrationWarning style".split(" ");B.push("innerText","textContent");B.forEach(function(a){new f(a,0,!1,a,null,!1,!1)});[["acceptCharset","accept-charset"],["className","class"],["htmlFor","for"],["httpEquiv","http-equiv"]].forEach(function(a){new f(a[0],1,!1,a[1],null,!1,!1)});["contentEditable","draggable","spellCheck","value"].forEach(function(a){new f(a,2,!1,a.toLowerCase(),null,!1,
!1)});["autoReverse","externalResourcesRequired","focusable","preserveAlpha"].forEach(function(a){new f(a,2,!1,a,null,!1,!1)});"allowFullScreen async autoFocus autoPlay controls default defer disabled disablePictureInPicture disableRemotePlayback formNoValidate hidden loop noModule noValidate open playsInline readOnly required reversed scoped seamless itemScope".split(" ").forEach(function(a){new f(a,3,!1,a.toLowerCase(),null,!1,!1)});["checked","multiple","muted","selected"].forEach(function(a){new f(a,
3,!0,a,null,!1,!1)});["capture","download"].forEach(function(a){new f(a,4,!1,a,null,!1,!1)});["cols","rows","size","span"].forEach(function(a){new f(a,6,!1,a,null,!1,!1)});["rowSpan","start"].forEach(function(a){new f(a,5,!1,a.toLowerCase(),null,!1,!1)});var N=/[\-:]([a-z])/g,O=function(a){return a[1].toUpperCase()};"accent-height alignment-baseline arabic-form baseline-shift cap-height clip-path clip-rule color-interpolation color-interpolation-filters color-profile color-rendering dominant-baseline enable-background fill-opacity fill-rule flood-color flood-opacity font-family font-size font-size-adjust font-stretch font-style font-variant font-weight glyph-name glyph-orientation-horizontal glyph-orientation-vertical horiz-adv-x horiz-origin-x image-rendering letter-spacing lighting-color marker-end marker-mid marker-start overline-position overline-thickness paint-order panose-1 pointer-events rendering-intent shape-rendering stop-color stop-opacity strikethrough-position strikethrough-thickness stroke-dasharray stroke-dashoffset stroke-linecap stroke-linejoin stroke-miterlimit stroke-opacity stroke-width text-anchor text-decoration text-rendering underline-position underline-thickness unicode-bidi unicode-range units-per-em v-alphabetic v-hanging v-ideographic v-mathematical vector-effect vert-adv-y vert-origin-x vert-origin-y word-spacing writing-mode xmlns:xlink x-height".split(" ").forEach(function(a){var b=
a.replace(N,O);new f(b,1,!1,a,null,!1,!1)});"xlink:actuate xlink:arcrole xlink:role xlink:show xlink:title xlink:type".split(" ").forEach(function(a){var b=a.replace(N,O);new f(b,1,!1,a,"http://www.w3.org/1999/xlink",!1,!1)});["xml:base","xml:lang","xml:space"].forEach(function(a){var b=a.replace(N,O);new f(b,1,!1,a,"http://www.w3.org/XML/1998/namespace",!1,!1)});["tabIndex","crossOrigin"].forEach(function(a){new f(a,1,!1,a.toLowerCase(),null,!1,!1)});new f("xlinkHref",1,!1,"xlink:href","http://www.w3.org/1999/xlink",
!0,!1);["src","href","action","formAction"].forEach(function(a){new f(a,1,!1,a.toLowerCase(),null,!0,!0)});var P={animationIterationCount:!0,aspectRatio:!0,borderImageOutset:!0,borderImageSlice:!0,borderImageWidth:!0,boxFlex:!0,boxFlexGroup:!0,boxOrdinalGroup:!0,columnCount:!0,columns:!0,flex:!0,flexGrow:!0,flexPositive:!0,flexShrink:!0,flexNegative:!0,flexOrder:!0,gridArea:!0,gridRow:!0,gridRowEnd:!0,gridRowSpan:!0,gridRowStart:!0,gridColumn:!0,gridColumnEnd:!0,gridColumnSpan:!0,gridColumnStart:!0,
fontWeight:!0,lineClamp:!0,lineHeight:!0,opacity:!0,order:!0,orphans:!0,tabSize:!0,widows:!0,zIndex:!0,zoom:!0,fillOpacity:!0,floodOpacity:!0,stopOpacity:!0,strokeDasharray:!0,strokeDashoffset:!0,strokeMiterlimit:!0,strokeOpacity:!0,strokeWidth:!0},sa=["Webkit","ms","Moz","O"];Object.keys(P).forEach(function(a){sa.forEach(function(b){b=b+a.charAt(0).toUpperCase()+a.substring(1);P[b]=P[a]})});var da=Array.isArray;d("<script>");d("\x3c/script>");d('<script src="');d('<script type="module" src="');d('" async="">\x3c/script>');
d("\x3c!-- --\x3e");d(' style="');d(":");d(";");d(" ");d('="');d('"');d('=""');d(">");d("/>");d(' selected=""');d("\n");d("<!DOCTYPE html>");d("</");d(">");d('<template id="');d('"></template>');d("\x3c!--$--\x3e");d('\x3c!--$?--\x3e<template id="');d('"></template>');d("\x3c!--$!--\x3e");d("\x3c!--/$--\x3e");d("<template");d('"');d(' data-dgst="');d(' data-msg="');d(' data-stck="');d("></template>");d('<div hidden id="');d('">');d("</div>");d('<svg aria-hidden="true" style="display:none" id="');
d('">');d("</svg>");d('<math aria-hidden="true" style="display:none" id="');d('">');d("</math>");d('<table hidden id="');d('">');d("</table>");d('<table hidden><tbody id="');d('">');d("</tbody></table>");d('<table hidden><tr id="');d('">');d("</tr></table>");d('<table hidden><colgroup id="');d('">');d("</colgroup></table>");d('function $RS(a,b){a=document.getElementById(a);b=document.getElementById(b);for(a.parentNode.removeChild(a);a.firstChild;)b.parentNode.insertBefore(a.firstChild,b);b.parentNode.removeChild(b)};$RS("');
d('$RS("');d('","');d('")\x3c/script>');d('function $RC(a,b){a=document.getElementById(a);b=document.getElementById(b);b.parentNode.removeChild(b);if(a){a=a.previousSibling;var f=a.parentNode,c=a.nextSibling,e=0;do{if(c&&8===c.nodeType){var d=c.data;if("/$"===d)if(0===e)break;else e--;else"$"!==d&&"$?"!==d&&"$!"!==d||e++}d=c.nextSibling;f.removeChild(c);c=d}while(c);for(;b.firstChild;)f.insertBefore(b.firstChild,c);a.data="$";a._reactRetry&&a._reactRetry()}};$RC("');d('$RC("');d('","');d('")\x3c/script>');
d('function $RX(b,c,d,e){var a=document.getElementById(b);a&&(b=a.previousSibling,b.data="$!",a=a.dataset,c&&(a.dgst=c),d&&(a.msg=d),e&&(a.stck=e),b._reactRetry&&b._reactRetry())};$RX("');d('$RX("');d('"');d(")\x3c/script>");d(",");var p=null,A=null,ra={useMemo:function(a){return a()},useCallback:function(a){return a},useDebugValue:function(){},useDeferredValue:m,useTransition:m,getCacheForType:function(a){if(!v)throw Error("Reading the cache is only supported while rendering.");var b=v.get(a);void 0===
b&&(b=a(),v.set(a,b));return b},readContext:X,useContext:X,useReducer:m,useRef:m,useState:m,useInsertionEffect:m,useLayoutEffect:m,useImperativeHandle:m,useEffect:m,useId:function(){if(null===A)throw Error("useId can only be used while React is rendering");var a=A.identifierCount++;return":"+A.identifierPrefix+"S"+a.toString(32)+":"},useMutableSource:m,useSyncExternalStore:m,useCacheRefresh:function(){return ia}},v=null;B=x.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;var M=B.ContextRegistry,
L=B.ReactCurrentDispatcher,ba={};w.renderToReadableStream=function(a,b,d){var c=ka(a,b,d?d.onError:void 0,d?d.context:void 0,d?d.identifierPrefix:void 0);return new ReadableStream({type:"bytes",start:function(a){ca(c)},pull:function(a){if(1===c.status)c.status=2,Q(a,c.fatalError);else if(2!==c.status&&null===c.destination){c.destination=a;try{ha(c,a)}catch(g){E(c,g),fa(c,g)}}},cancel:function(a){}},{highWaterMark:0})}});
})();
